[project]
name = "bing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bingads>=13.0.24.1",
    "setuptools>=75.8.0",
]
